name: 'Teams Notification'
description: 'Notify a given channel in MS Teams that a GHA deployment was a success/failure'
inputs:
  status:
    description: 'The workflow status'
    # One of: success, failure, neutral, cancelled, skipped, timed_out, or action_required
    required: true
  webhook-url:
    description: 'The Microsoft Teams incoming webhook URL'
    # https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook#create-an-incoming-webhook
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
