name: 'Teams Notification'
description: 'Notify a given channel in MS Teams that a deployment was a success/failure'
inputs:
  MS_TEAMS_WEBHOOK_URL:
    description: 'the url for the Teams incoming webhook'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Microsoft Teams Notification
      uses: skitionek/notify-microsoft-teams@master
      with:
        webhook_url: ${{ inputs.MS_TEAMS_WEBHOOK_URL }}
        #        https://github.com/Skitionek/notify-microsoft-teams/blob/master/dist/index.js#L1175
        #        TODO workflow name
        #        TODO workflow state (failure || success)
        #               job.status
        #        TODO link to repo
        #                name = github.event.repository.full_name
        #                link = github.event.repository.html_url
        #        TODO link to run
        #                link = https://github.com/${repoName}/actions/runs/${runId}?
        #        TODO commit message and link to commit (compare button)
        #                sha = github.event.after
        #                compare button = github.event.compare (link)
        #        TODO deployment number (and link)
        #        TODO pushed by author (and link)
        #               pushed by = github.event.sender.login
        #               link      = github.event.sender.url
        raw: >-
          {
              "$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
              "@type": "AdaptiveCard",
              "version": "1.2",
              "@context": "http://schema.org/extensions",
              "themeColor": "${{ (job.status == 'success' && '4F7942') || 'FD3004' }}",
              "summary": "GitHub action was a ${{job.status}}!",
              "body": [
                  {
                      "type": "TextBlock",
                      "size": "Medium",
                      "weight": "Bolder",
                      "text": "GitHub Actions"
                  },
                  {
                      "type": "ColumnSet",
                      "columns": [
                          {
                              "type": "Column",
                              "items": [
                                  {
                                      "type": "Image",
                                      "style": "Person",
                                      "url": "https://raw.githubusercontent.com/byu-oit/github-action-teams/master/success.jpg",
                                      "size": "Medium"
                                  }
                              ],
                              "width": "auto"
                          },
                          {
                              "type": "Column",
                              "items": [
                                  {
                                      "type": "TextBlock",
                                      "text": "The **Deploy** workflow on [byu-oit/example]() was **successful**",
                                      "wrap": true
                                  }
                              ],
                              "width": "stretch"
                          }
                      ]
                  },
                  {
                      "type": "TextBlock",
                      "text": "head commit message",
                      "wrap": true
                  },
                  {
                      "type": "FactSet",
                      "facts": [
                          {
                              "title": "Deployment:",
                              "value": "[#20]()"
                          },
                          {
                              "title": "Commit:",
                              "value": "[123sha]()"
                          },
                          {
                              "title": "Pushed By:",
                              "value": "[redjojo]() Joanna hugo"
                          }
                      ]
                  }
              ],
              "actions": [
                  {
                      "type": "Action.OpenUrl",
                      "title": "View Run",
                      "url": "https://github.com/byu-oit/testing-github-actions/runs/4121830145?check_suite_focus=true",
                      "style": "positive"
                  }
              ]
          }

