name: 'Teams Notification'
description: 'Notify a given channel in MS Teams that a deployment was a success/failure'
inputs:
  MS_TEAMS_WEBHOOK_URL:
    description: 'the url for the Teams incoming webhook'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Microsoft Teams Notification
      uses: skitionek/notify-microsoft-teams@master
      with:
        webhook_url: ${{ inputs.MS_TEAMS_WEBHOOK_URL }}
        raw: >-
          {
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "${{ (job.status == 'success' && '4F7942') || 'FD3004' }}",
            "summary": "GitHub action was a ${{job.status}}!",
            "sections": [{
              "activityTitle": "GitHub action was a ${{job.status}}!",
              "facts": [{
                "name": "Repository",
                "value": "${{github.event.repository.name}}"
              },
              {
                "name": "Commit Message",
                "value": "${{env.COMMIT_MESSAGE}}"
              }],
              "markdown": true
            }]
          }

