on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Send a msg to Teams
    steps:
      - uses: actions/checkout@v1
      - id: send-msg
        uses: ./
        with:
          MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}