name: Test

on: [push]

jobs:
  test_success:
    runs-on: ubuntu-latest
    name: Send a SUCCESS msg to Teams
    steps:
      - uses: actions/checkout@v1
      - id: send-msg
        uses: ./
        with:
          MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

  test_failure:
    name: Send a FAILURE msg to Teams
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating_system: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Fail On Purpose
        working-directory: src
        run: npm audit --audit-level=critical

      - name: notify MS Teams
        uses: ./
        with:
          MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}